spring:
  profiles:
    active: dev
  application:
    name: news-summary

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_schema: newsfeeds
    show-sql: true

news:
  api:
    key: ${NEWS_API_KEY}
    base-url: https://newsapi.org/v2

# UptimeRobot 용
management:
  endpoints:
    web:
      exposure:
        include: health

openai:
  api:
    key: ${OPENAI_API_KEY}
    base-url: https://api.openai.com/v1

springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    path: /swagger

cors:
  allowed-origins: ${ALLOWED_ORIGINS}
  base-url: https://api.openai.com/v1